### ISSUE TITLE
How to I run generated executable?

### ISSUE THREAD

**Issue by holazollil** [edrosten/libcvd#12]
I use ubuntu 14.04 and gcc version 4.8.4. I download libcvd and run ./configure & make & make install.

Now I want to run  generated executables with ubuntu terminal. I attach Inca IC-3562 device to pc. I open a terminal and run ./progs/calibrate,
response is 

opening v4l2:///dev/video0
V4LBuffer: No colourspace  on /dev/video0 matching None

How can I run this calibration exe?

**Comment by edrosten** [comment]
On 23 July 2015 at 16:31, holazollil <notifications@github.com> wrote:

> I use ubuntu 14.04 and gcc version 4.8.4. I download libcvd and run
> ./configure & make & make install.
>
> Now I want to run generated executables with ubuntu terminal. I attach
> Inca IC-3562 device to pc. I open a terminal and run ./progs/calibrate,
> response is
>
> opening v4l2:///dev/video0
> V4LBuffer: No colourspace on /dev/video0 matching None
>

The problem is that the calibration program requires greyscale video and
the camera doesn't provide it. The webcam almost certainly provides yuv422.
You can do the conversion by specifying the video device as:

colourspace:[from=yuv422]//v4l2:///dev/video0

-Ed

**Comment by holazollil** [comment]
I change 35-40 th lines in calibrate.cxx below as :

// global configuration variables, can be set via command line options
#ifdef CVD_HAVE_QTBUFFER
string videoDevice = "colourspace:[from=yuv422]//qt://0";
#else
string videoDevice = "colourspace:[from=yuv422]//v4l2:///dev/video0";
//"v4l2:///dev/video0";
#endif

It works now. Thank you.

2015-07-23 18:52 GMT+03:00 Edward Rosten <notifications@github.com>:
