### ISSUE TITLE
Installation in windows

### ISSUE THREAD

**Issue by holazollil** [edrosten/libcvd#13]
I have TooN and pthread in windows. I try to use libcvd, but I don't know what I should do. I downloaded libcvd code. How can I install in windows? 

I open cygwin and run ./configure; make; make install;. It generates only .dll.a files not .lib.

**Comment by edrosten** [comment]
On 1 August 2015 at 09:37, holazollil <notifications@github.com> wrote:

> I have TooN and pthread in windows. I try to use libcvd, but I don't know
> what I should do. I downloaded libcvd code. How can I install in windows?
>
> I open cygwin and run ./configure; make; make install;. It generates only
> .dll.a files not .lib.
>

Do you want to be able to link itwith visual studio? If so, this won't
work, since the C++ ABI is different and you can't get C++ DLLs from GCC
working with VS. If you're sticking inside CYGWIN, then I don't believe the
.lib is required.

I've not really got much experience with Windows. There's some VS build
files provided. They're old, but they ought to import correctly. libCVD is
currently undergoing a rewrite for C++14. There are no windows build files
yet, but it ought to be much easier to set up than the old version since
all the platform compatibility stuff has been ripped out of libCVD since
C++14 provides it all now.

If you're interested in going down that route, and especially if you're
interested in helping keep the Windows build files up to date, then please
let me know.

-Ed

**Comment by holazollil** [comment]
I use unity + opencv(using ndk) for AR apps.Now, I want to use this PTAM code for android AR application. Android PTAM is not available now. I plan to generate .so file using c++ PTAM code.

I think I use PTAM+Unity for android apps by this way. Am I wrong?

**Comment by edrosten** [comment]
That sounds reasonable. PTAM uses a few other libraries I beliece so you'll
have to compile the .so for them too if applicable.

-Ed

**Comment by holazollil** [comment]
ok. I will try.

2015-08-31 15:57 GMT+03:00 Edward Rosten <notifications@github.com>:

> That sounds reasonable. PTAM uses a few other libraries I beliece so you'll
> have to compile the .so for them too if applicable.
>
> -Ed
>
>
